// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_upgrades_complete = "CgkI0rjW_-oREAIQCA"; // <GPGSID>
        public const string achievement_ahoy_capn = "CgkI0rjW_-oREAIQAg"; // <GPGSID>
        public const string achievement_a_boatload_of_gold = "CgkI0rjW_-oREAIQCg"; // <GPGSID>
        public const string achievement_no_prey_no_pay = "CgkI0rjW_-oREAIQCw"; // <GPGSID>
        public const string achievement_scuttle_th_ship = "CgkI0rjW_-oREAIQBA"; // <GPGSID>
        public const string achievement_give_me_th_booty = "CgkI0rjW_-oREAIQAw"; // <GPGSID>
        public const string achievement_lets_yeet_this_wheat = "CgkI0rjW_-oREAIQBw"; // <GPGSID>
        public const string leaderboard_richest_pirate = "CgkI0rjW_-oREAIQAA"; // <GPGSID>
        public const string leaderboard_most_enemy_ships_sunk = "CgkI0rjW_-oREAIQAQ"; // <GPGSID>
        public const string achievement_ram_th_scoundrels = "CgkI0rjW_-oREAIQDA"; // <GPGSID>
        public const string achievement_no_quarters_given = "CgkI0rjW_-oREAIQBQ"; // <GPGSID>
        public const string achievement_not_a_scratch_to_be_seen = "CgkI0rjW_-oREAIQDQ"; // <GPGSID>
        public const string achievement_scourge_of_the_seven_seas = "CgkI0rjW_-oREAIQBg"; // <GPGSID>

}

